// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/ink-yht/hure/internal/repository/dao/user_dao"
	"github.com/ink-yht/hure/internal/repository/user_repo"
	"github.com/ink-yht/hure/internal/service/user_service"
	"github.com/ink-yht/hure/internal/web/user_web"
	"github.com/ink-yht/hure/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	logger := ioc.InitLogger()
	v := ioc.InitMiddleWares(logger)
	db := ioc.InitDB()
	adminDao := user_dao.NewAdminDAO(db)
	adminRepository := user_repo.NewAdminRepository(adminDao)
	adminService := user_service.NewAdminService(adminRepository)
	adminHandler := user_web.NewAdminHandler(adminService, logger)
	engine := ioc.InitWebServer(v, adminHandler)
	return engine
}
